### ISSUE TITLE
Grave accent (again)

### ISSUE THREAD

**Issue by gregorycrane** [jtauber/greek-accentuation#19]
I am getting error messages when I try to ask for the accent on a word with a grave accent.

>>> from greek_accentuation.characters import *
>>> from greek_accentuation.syllabify import *
>>> from greek_accentuation.accentuation import *
>>> display_accentuation(get_accentuation(('τὴν')))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/greek_accentuation/accentuation.py", line 68, in display_accentuation
    return accentuation.name.lower()
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by jtauber** [comment]
Remember that the point of `get_accentuation` is to tell you the type of word accentuation (e.g. "oxytone") of a normalized word in isolation. See my comments on #17
