### ISSUE TITLE
consider containing package

### ISSUE THREAD

**Issue by jtauber** [jtauber/greek-accentuation#2]
I've often regretted that the three modules in `greek-accentuation` don't have a containing package.

What should it be called though? `greek_accentuation`?

This would mean
- `characters` would become `greek_accentuation.characters`
- `accentuation` would become `greek_accentuation.accentuation`
- `syllabify` would become `greek_accentuation.syllabify`

Any other name suggestions? The second seems a little awkward.

Might be a good final step before declaring 1.0.0 😄

**Comment by kylepjohnson** [comment]
Hi James, I think that's a fine name. I like to import my models in the following way. Is this along the lines of what you were thinking about?

``` python
>>> from greek_accentuation import characters
>>> from greek_accentuation import syllabify
>>> from greek_accentuation import accentuation
```

Your project is definitely due for a 1.0 release! I am also thinking about including it by default into the cltk (I don't know if that changes anything for you). @j-duff can chime in, too.

**Comment by jtauber** [comment]
Yes, you could do

``` python
from greek_accentuation import characters
```

or things like

``` python
from greek_accentuation.characters import strip_accents
```

The other thing I _could_ do if there are no name clashes across the three modules is have `greek_accentuation/__init__.py` import the modules so things like `from greek_accentuation import strip_accents` would work.

I'll also take the opportunity to move over some (but not all) of the stuff in https://github.com/jtauber/greek-inflexion/blob/master/accent.py to this package.

**Comment by kylepjohnson** [comment]
Sounds perfect.

> The other thing I could do if there are no name clashes across the three modules is have

I personally disfavor these, as it complicates debugging. However there are times it's called for, I'm sure.

**Comment by jtauber** [comment]
Done (minus any magic in `__init__.py`) and released as 1.0.0

**Comment by jtauber** [comment]
@kylepjohnson I'd be delighted for it to be included in CLTK by default.

**Comment by kylepjohnson** [comment]
:tada:

Let's add it when we push Jack's work!

My request for you is to think about what kind of info we should include in the cltk docs. We should do more than just a link to your site, however we don't need to explain every nuance, either. Let us know (maybe Jack can help) or make a PR yourself.

**Comment by jtauber** [comment]
Yeah, there are a lot of "internal" functions that aren't likely to be useful to most people. I'll think about some key functions that form the "core API" and write up some docs on those which I'll include in this repo but which you can re-use in CLTK.
